### ISSUE TITLE
Incorrect Time Resolution for Averaging Data Using pytplot.tplot_math.avg_res_data()

### ISSUE THREAD

**Issue by pspathare** [spedas/pyspedas#1046]
I’m working with SPAN-I solar wind data and averaging a variable over 60 seconds using this function:
pytplot.tplot_math.avg_res_data(tvar, res, newname=None, new_tvar=None)
I’ve set res = 60 for 1-minute averaging, but the resulting time resolution is 4 minute , not 1 minute. The data array length is 271,846, and the instrument records every 3.495 seconds. For 1-minute averages, the array length should be around 15,840, but I’m getting 4,530 (which corresponds to 240 seconds).

Maybe I’m not using pytplot.tplot_math.avg_res_data() correctly. I’d really appreciate your help with this. I’ve attached my code for reference.

**************************************************************************************************************************
import pyspedas
import pytplot 
import numpy as np
import pandas as pd
from pytplot import tplot
from pytplot import get_data
import datetime

spi_vars = pyspedas.psp.spi(trange=['2021-04-24/00:00:00','2021-05-04/23:59:00'], datatype='sf00_l3_mom', level='l3', time_clip=True)
Solar_wind_speed_data = get_data('psp_spi_VEL_RTN_SUN')
time_sw_spi = Solar_wind_speed_data.times
datetimes_spi = [datetime.datetime.utcfromtimestamp(ts) for ts in time_sw_spi]
#velocity component
split_data_spi = pytplot.tplot_math.split_vec('psp_spi_VEL_RTN_SUN')
v_r_spi =pytplot.data_quants['psp_spi_VEL_RTN_SUN_x'].values
v_t_spi=pytplot.data_quants['psp_spi_VEL_RTN_SUN_y'].values
v_n_spi=pytplot.data_quants['psp_spi_VEL_RTN_SUN_z'].values
v_mag_spi_val= np.sqrt(v_r_spi**2 + v_t_spi**2 + v_n_spi**2)
#Solar wind speed
pytplot.store_data('v_mag_spi',data = {'x' :datetimes_spi, 'y': v_mag_spi_val})
#averaging the data
pytplot.tplot_math.avg_res_data('v_mag_spi', 60,'v_mag_spi_avg')
time_spi = get_data('v_mag_spi_avg').times
datetimes_avg_spi_sw = [datetime.datetime.utcfromtimestamp(ts) for ts in time_spi]
#Averaging with other method
df = pd.DataFrame({'Time': datetimes_spi, 'Value': v_mag_spi_val})
df.set_index('Time', inplace=True)
df_resampled = df.resample('60S').mean()
#Plotting
tplot('v_mag_spi')

**Comment by jameswilburlewis** [comment]
I couldn't successfully reproduce your example...there was an error at this line:

`v_mag_spi_val= np.sqrt(v_r_spi2 + v_t_spi2 + v_n_spi**2)`

because v_r_spi2 isn't defined.

However, looking at the code to avg_res_data, I can see why it might not be working now.   I think it assumes that the timestamps are stored internally as Unix times in seconds -- now we're using numpy datetime64 objects as the internal representation, and I'm not sure that the xarray coarsen() method will do the right thing the way it's being called.

We have another time averaging routine that might work better.  Can you try

`pyspedas.avg_data('v_mag_spi', res=60, newname='v_mag_spi_avg')`

and let me know if that gives something closer to what you're expecting?

**Comment by pspathare** [comment]
Apologies for late response.
I tried the following routine:
pyspedas.avg_data('v_mag_spi', res=60, newname='v_mag_spi_avg')

It worked. Thank You😊 .

**Comment by jameswilburlewis** [comment]
I've added a note to the avg_res_data()  docstring that pyspedas.avg_data() is nearly always a better choice, due to some restrictive assumptions that are necessary in order for avg_res_data() to work as expected.
