### ISSUE TITLE
For poes data

### ISSUE THREAD

**Issue by chondrite1230** [spedas/pyspedas#160]
Hello all,
 
I am trying to use POES-MEPED data using pyspedas.
I did >>>pyspedas.poes.load(trange)
But I found pyspedas does not load the POES flux data for example, 'mep_ele_flux'.
When I read the individual CDF files, there is 'mep_ele_flux' variable.

Could you check all the POES data is properly loaded?

Best regards,
Inchun

**Comment by supervised** [comment]
Hello!

The mep_ele_flux variable is labeled as 'support_data' in the CDF, so it's not loaded by default. To load it, use:

`pyspedas.poes.load(trange, get_support_data=True)`

Though I suggest using the instrument load routine `pyspedas.poes.sem` instead of calling load directly, e.g., 

`pyspedas.poes.sem(trange, get_support_data=True)`

Eventually we'll have some post-processing code in there that'll be useful.

**Comment by chondrite1230** [comment]
Thank you for the comment!!
I still don't understand what is difference between poes.load and poes.sem. 
But I will use poes.sem as you mentioned.

It really helps me to do work!

Cheers!

**Comment by chondrite1230** [comment]
Sorry for reopening the issue.

I tried poes.sem for other probes like noaa18, 17, metop1,2.
It seems probe option does not work. It only load noaa19.

If I use poes.load with probe option, it downloads and merges all registered probe data.

I think it would be better to use poes.load so far.

**Comment by chondrite1230** [comment]
Thank you for explaining and debugging!
I hope the sem routine developed soon!!!
cheers!
