### ISSUE TITLE
In the case of unavailble data...

### ISSUE THREAD

**Issue by qudsiramiz** [spedas/pyspedas#273]
Consider the following code:
```
import pyspedas as spd
import pytplot as ptt

trange = ['2017-09-01 09:58:30', '2017-09-01 09:59:30']
_ = spd.mms.fpi(trange=trange, probe=3, data_rate='brst', level='l2',
                datatype='dis-moms', varnames='mms3_dis_bulkv_gse_brst', time_clip=True,
                latest_version=True)
fpi_time_unix = ptt.get_data(mms_fpi_varnames[0])[0]
fpi_v_gse = ptt.get_data(mms_fpi_varnames[0])[1:][0]

fpi_time_utc = spd.time_datetime(fpi_time_unix)

print(f"Start time: {fpi_time_utc[0].strftime('%Y-%m-%d %H:%M:%S')}")
print(f"End time: {fpi_time_utc[-1].strftime('%Y-%m-%d %H:%M:%S')}")
```

Given that ```trange = ['2017-09-01 09:58:30', '2017-09-01 09:59:30']```, one would expect the code to print those dates. Or, in the case that 'brst' data is not available, the code should should either throw an **error** or **NaNs**.

However, in this case the dates are: ```Start time: 2017-09-01 09:17:03,  End time: 2017-09-01 09:18:02```.

From what I can surmize, it appears that in case the burst data is not available for the specified time range. the function looks for the  data closest to the specified time range and outputs those times and corresponding data, which was unexpected for me, specially because I specified the ```time_clip``` parameter.

This made me wonder, if this is how the code is supposed to work, or if this is a bug in the code.

**Comment by supervised** [comment]
Hello - thanks for the question/bug report!

This behavior is because we don't know the full time range of the data in burst mode files (only the start time, which is in the file name) - so when we request burst mode data from the SDC, we ask for all burst data from the start of the day, then filter the results down to the requested start time minus some padding (at least, that's the way it's supposed to work). It's kludgy, and can end up downloading data outside the time range, but if data does exist for your time range, it should be able to load it (even though we only know the start times in the files). 

I am surprised that it picked up data from over 40 minutes from the start time though; I thought the padding was more like 5 or 10 minutes, so I'm going to have to look into this further. The error messages here can definitely be improved as well. 

Thanks again!

**Comment by qudsiramiz** [comment]
> but if data does exist for your time range, it should be able to load it (even though we only know the start times in the files).

Yep, if the data exists, then it is able to load the correct data without any problem. The problem arises only when we don't have data.

A padding of 5 or so minutes makes sense, however, this makes me wonder if it will be possible to add a key word like ```dt_pad``` in some units (preferably minutes) over which the code would search for the relevant data if the data isn't available within the specified ```trange```.

This might be a lot more involved than what I am thinking, but will be great to have this functionality.

**Comment by supervised** [comment]
I looked into this more, and I was wrong about the padding - it's a little more complicated. I'm hesitant to make changes to the core MMS load routine due to the high possibility of me introducing a new bug. 

In IDL, we have a tool to query the MMS burst events database. It should tell us not just where the burst data starts/stops, but also provide a description of the interval from the SITL who made the burst selection.  I'll move that functionality over so it's available in Python as well.

**Comment by qudsiramiz** [comment]
That sounds like a reasonable approach. Thank you!

**Comment by jameswilburlewis** [comment]
It would be good to address the original issue with time_clip.  It is confusing to have data returned which falls well outside the interval specified by the user.   It is somewhat complicated by the fact that we don't know the end time of a particular data file.   I would suggest something like this:  add some padding to the end time of the trange value passed in (may vary by survey mode, perhaps 10 minutes or so for burst?   Then we can be sure that we're not losing any data that the user might have wanted.....now if time_clip is True, go ahead and clip it to the original, unpadded trange.
