### ISSUE TITLE
MMS FPI DIS moms omni spin avg doesn't seem to be averaged

### ISSUE THREAD

**Issue by kileyy10** [spedas/pyspedas#284]
The FPI DIS moments energy spectra data does not seem to be spin-averaging when the omni product is loaded.
`dis_data = pyspedas.mms.fpi(trange=[date_start_str, date_end_str], datatype=['dis-moms'],
                                center_measurement=True, data_rate='fast')`
`t, y, z = get_data('mms1_dis_energyspectr_omni_fast')`
A difference on the time stamps results in a 4.5 second interval, which is the non-omni sampling interval.

**Comment by supervised** [comment]
I think FPI captures several omni-directional measurements in less than a spin; this is because DIS is made up of eight different spectrometers facing in different directions:

https://lasp.colorado.edu/galaxy/display/MFDPG/2.1+FPI+Instrument+and+Data+Collection+Description

So spin-averaging isn't required to get the omni-directional measurements.
