### ISSUE TITLE
Port gse2sse from IDL to pyspedas

### ISSUE THREAD

**Issue by Plasma92** [spedas/pyspedas#324]
The coordinate transformation gse2sse is unavailable in pyspedas. It's useful for KAGUYA and ARTEMIS spacecraft missions 

It should also have an IDL versus Python validation test, following the structure of themis/tests/validation/tests_dsl_cotrans.py

**Comment by clrussell90404** [comment]
Hi Jim,

Jiashu and I are meeting later today to work on this.

I'm still struggling trying to get this new 3d tplot variable. I tried the following routine, but it didn't work correctly.

function array_merge,arr2d,arr1d
  d1=size(arr2d,/dimensions)
  d2=size(arr1d,/dimensions)
  arr3d=dblarr(d1[0],d1[1],d2[0])
  for i=0,d1[0]-2 do begin
    for j=0,d1[1]-1 do begin
      for k=0,d2[0]-1 do begin
        arr3d[i,j,k] = [arr2d[i,j],arr1d[k]]
      endfor
    endfor
  endfor
return, arr3d
end

I'm trying to get create an array with dimensions [215, 10, 16] from [215, 10] and [16]. I'm fairly certain my mastercdf is correct and creating the cdf seems to be correct.  But when I read the l2 cdf I get

X   double [215]
Y   double [215, 10]
V   double [215, 10]

Instead of the original l2 tplot variable that Vassilis created:
X   double [215]
Y   double [215, 10, 16]
V   double [215, 10]

Would something like the following work the same?

X   double [215]
Y   double [215, 10]
V   double [215, 10]
Z   double [16]

I do have an explanation from Vassilis for the tplot variable he created. Maybe cdf2tplot doesn't handle 3d? I'll forward Vassilis's email.

Is there someone who can help me figure this out?

Thanks!

Cindy


________________________________

**Comment by jameswilburlewis** [comment]
pyspedas version 1.4.28, just released to pypi, contains cotrans routines gse2sse and sse2sel, and associated tests.  The interfaces to each of these routines is very similar to the IDL implementation, although we will probably be simplifying the pyspedas versions  by loading support data internally, rather than passing additional tplot variables as parameters.
