### ISSUE TITLE
Create VirES example notebooks

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#387]
I recently created a wrapper for VirES data:

https://github.com/spedas/pyspedas/tree/master/pyspedas/vires

Most - if not all - of the data products should be available through this wrapper. They have numerous examples that we can re-create with less code (due to our simple interface). I think we should create some notebooks showing these examples using PySPEDAS

For more info, see:
https://github.com/ESA-VirES/VirES-Python-Client
https://vires.services/

**Comment by jameswilburlewis** [comment]
The VIRES service requires users to sign up for an account and generate an access token.  We can't easily provide that in a notebook environment without leaking our own token, so it may not be worth it to develop a notebook.  I've added a VIRES page on readthedocs with pointers to the token management docs, and a few examples, so that should be enough to get people started.
