### ISSUE TITLE
Improve the error handling in the CDAWeb GUI interface

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#389]
The CDAWeb GUI interface doesn't work by default now:

> >>> from pyspedas.cdagui.cdagui import cdagui
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/eric/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pyspedas/cdagui/cdagui.py", line 25, in <module>
>     from PyQt5.QtCore import Qt, QDate, QCoreApplication
> ModuleNotFoundError: No module named 'PyQt5'

This is because we no longer require PyQt (due to moving away from Qt in PyTplot). These routines should be updated to gracefully handle the case of PyQt not being installed, and provide installation instructions for PyQt instead of crashing.

**Comment by jameswilburlewis** [comment]
For the short term, we can wrap the failing import line in a try/except block, and give instructions for installing Qt in the exception handler.  Here's an example from MMS:

```
try:
    import spacepy.coordinates as coord
except ImportError:
    logging.error('SpacePy must be installed to use this module.')
    logging.error('Please install it using: pip install spacepy')

```

Longer term:  as we discussed a bit a few months ago, we might want to make a separate package and repo for PySPEDAS GUI tools.   The ERG folks are nearly finished with a Python version of the ISEE 3D GUI particle distribution visualization tool (I think using Pyside6, an alternate implementation of Qt), so maybe we could rework the CDAWeb GUI to use the same backend, and these two tools would be a good start for a pyspedas-gui package.

**Comment by nickssl** [comment]
Added a message. If PyQt5 is not installed in the user's system, they can install it using:
pip install pyqt5

**Comment by supervised** [comment]
> Added a message. If PyQt5 is not installed in the user's system, they can install it using: pip install pyqt5

Does this actually work anywhere? The installation process for PyQt5 was always much, much more complicated for me

**Comment by nickssl** [comment]
Perhaps you can try it again and see what happens. One year and a half is a very long time for python!

**Comment by supervised** [comment]
> Yes, it works for me on all the systems I have tried it on (Windows, Mac, Ubuntu, Chromebook with linux installed). What exactly is the problem you have? [image: cdagui.png]

On my M1 mac, pip (22.0.4) freezes on "Preparing metadata" when trying to install it:

> (base) eric@erics-mac ~ % pip install pyqt5
> Collecting pyqt5
>   Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... -

**Comment by supervised** [comment]
When you tested on Ubuntu, did you test on a completely new machine (or VM)? I think there were system libraries that needed to be installed (e.g., libgl1-mesa-glx), and GUIs would crash without them. I would always have to install gedit before installing PyQt5 to get it to work on Ubuntu.

**Comment by nickssl** [comment]
I just tried it on a fairly new Ubuntu installation where I did not had pyspedas installed yet. It was missing a linux package and I had to run this additional command:

sudo apt install libxcb-xinerama0

After that, everything worked correctly. 
I just created a new python environment and I run:

pip install pyqt5
pip install pyspedas
python3

Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyspedas.cdagui.cdagui import cdagui
>>> x=cdagui()

The window opened without problems and everything worked as expected. 

![Screenshot from 2023-06-02 12-50-56](https://github.com/spedas/pyspedas/assets/34072991/f3fe8403-3ca4-4a62-b74e-d8b2140b3fae)

**Comment by nickssl** [comment]
The image above is Ubuntu 22.04.2 LTS, on a separate disk on my PC, used mainly for testing.

**Comment by nickssl** [comment]
For the Mac M1, you can use a Rosetta terminal (Finder->Applications->Utilities right click on Terminal, select Get Info, check "Open using Rosetta").

Then you just install pyspedas and pyqt5, you don't need anything else, at least my system didn't need anything else.

pip install pyspedas
pip install pyqt5

Everything should work now.

![Screenshot 2023-06-02 at 2 22 01 PM (2)](https://github.com/spedas/pyspedas/assets/34072991/cc379e6d-b87e-4d6e-b01c-1d9ba1b3396d)

![Screenshot 2023-06-02 at 2 11 25 PM_](https://github.com/spedas/pyspedas/assets/34072991/7bb0f192-3ead-4dfe-95cc-454e1feaf49f)

**Comment by nickssl** [comment]
By the way, when I google "best python library for gui 2023", most results have pyqt5 as the best one. For example:

https://www.unite.ai/10-best-python-libraries-for-gui/
https://www.activestate.com/blog/top-10-python-gui-frameworks-compared/
https://www.vpsserver.com/best-python-libraries-for-gui/
https://python.plainenglish.io/top-10-python-gui-libraries-for-modern-development-d6f1bb2c3bb7

For pyspedas, Tkinter also seems to be a good candidate.

**Comment by jameswilburlewis** [comment]
It sounds like there are enough potential installation issues with pyqt5 that we ought to collect them in one place (somewhere on the SPEDAS wiki, maybe), then refer to that URL in the message for when the pyqt5 import fails.

The ISEE-3D tool the ERG team is working on is based on pyside6, which I think is pretty much the same as pyqt5 except with a slightly different license.   But I imagine one would face similar installation issues as we're seeing with pyqt5, even if the internal implementation is a bit different.   So I think that tool and others like it should go in a separate package, in order to keep heavy or potentially problematic dependencies out of the core spedas package.   

Tkinter might be a good choice for core pyspedas tools that don't need much in the way of advanced GUI features -- CDAWeb or HAPI interfaces probably don't need much more than buttons and list boxes.

**Comment by nickssl** [comment]
Yes, I will create a GUI for CDAWeb using tkinter.

**Comment by supervised** [comment]
> The ISEE-3D tool the ERG team is working on is based on pyside6, which I think is pretty much the same as pyqt5 except with a slightly different license. But I imagine one would face similar installation issues as we're seeing with pyqt5, even if the internal implementation is a bit different. So I think that tool and others like it should go in a separate package, in order to keep heavy or potentially problematic dependencies out of the core spedas package.

My suggestion is to make any GUIs (regardless of which frameworks are used) separate packages that depend on pyspedas/pytplot, and not have GUI code inside pyspedas (since it unnecessarily complicates the dependencies, and most users will never use it).

**Comment by nickssl** [comment]
I disagree. I don't see the point in splitting one project into multiple projects. I think even the pyspedas examples should be in a folder inside pyspedas, the same way we have the cribs inside IDL SPEDAS. In my opinion, the ideal would be having pytplot inside pyspedas, too, except that this was started by someone else, so this decision is not up to us. We already have 4 projects, and they are basically a single project, they are not 4 independent projects having different goals.

**Comment by nickssl** [comment]
For example, every time a bug is fixed in pytplot, we also have to create a new version of pyspedas with updated requirements to the new version of pytplot. It would be easier if pytplot was inside pyspedas. The same is true for the two separate example projects, but usually we don't even update their requirements, which can leave them broken. So we actually have to build 4 different new releases for a single bug fix! This seems unnecessary, especially since the whole thing is a single project, with a single goal, being developed by a single team.

**Comment by nickssl** [comment]
Tkinter is part of the python language, no additional requirements are needed.

PyQt5 is an additional requirement, and we don't really need it. However, pyqt5 is widely used, pyqt is available since 1998, and it is a good idea if we make sure that pyspedas is compatible with it, even if we don't require it and we don't use it. If we have major conflicts with Qt, then I think we should try to resolve these conflicts because pyqt is a much larger and much older project than pyspedas, and some users might have installed other python projects that use it.

https://en.wikipedia.org/wiki/PyQt

**Comment by supervised** [comment]
@jameswilburlewis is this GUI stuff high priority? From looking at the issues list, it seems like we have more important things to do

**Comment by jameswilburlewis** [comment]
I think it's worthwhile to have a couple of simple GUI tools for CDAWeb and
HAPI data retrieval if it can be done without introducing complicated
dependencies.   But yeah, anything more complicated than that can probably
wait, since we have bigger fish to fry right now, and I'm in favor of
having that stuff be a separate package for the sake of dependency
management.

**Comment by nickssl** [comment]
New version of the GUI uses Tkinter, which is included in python.
No additional requirements are needed.
PyQt5 is no longer used or required.
