### ISSUE TITLE
`pyspedas.wind.load` is given unrecongnized keyword "mastercdf"

### ISSUE THREAD

**Issue by STBadman** [spedas/pyspedas#434]
On Line 89 of [`pyspedas.wind.load`](https://github.com/spedas/pyspedas/blob/master/pyspedas/wind/load.py), `cdf_to_tplot` is called with a keyword `mastercdf` which does not appear to be a valid keyword for that function (https://pytplot.readthedocs.io/en/latest/reading_in_data.html). This causes all wind `load` calls to fail!

Is this a deprecated keyword? I'm not sure what a master CDF file is meant for. 

If the fix is as simple as removing the keyword I'm happy to make the PR, but wasn't sure if there is anything else in there that would break.

**Comment by jameswilburlewis** [comment]
It sounds like you need to upgrade to a later version of the pytplot-mpl-temp package.  I believe the mastercdf keyword in cdf_to_tplot was introduced in version 2.1.22 in mid-March 2023, current version in pypi is version 2.1.28

Master CDFs are necessary for loading many WIND data sets, because the data CDFs at SPDF are often missing a great deal of metadata.   The idea is that rather than reprocessing an entire missions' worth of data CDFs to fix metadata problems, the fixes can be made to a metadata-only CDF.  SPDF maintains and hosts master CDFs for most of their CDF holdings.

But thanks for letting us know that the documentation at readthedocs.io is out of date for pytplot!   I will open a separate issue to get that fixed.

**Comment by STBadman** [comment]
Thanks @jameswilburlewis for the clarification and explanation of their purposes.  I did that upgrade and the wind routines work now. 

I did first assume that upgrading pytplot itself would solve that issue but it seems i had to explicitly upgrade `pytplot-mpl-temp` - is that as intended or should that upgrade be part of the wheels of pytplot itself?

**Comment by supervised** [comment]
pytplot-mpl-temp (in PyPI) is the Matplotlib version of pytplot. pytplot (in PyPI) is the deprecated, Qt version of pytplot. I suggest using the mpl version until we move it to the official version.
