### ISSUE TITLE
Problem using cdflib in cdf_to_tplot

### ISSUE THREAD

**Issue by xnchu** [spedas/pyspedas#50]
The epoch is converted to unix_time at line 195 in cdf_to_tplot.py
If cdflib is used, it is converted using function unixtime at line 192 in epochs.py. 
The problem is line 222: 
unixtime.append(datetime.datetime(*date).timestamp())
It assumes local time instead of UTC. Therefore, the time is offset by your local time. 
The codes to reproduce the error is attached below. 
The result should be 2020-01-01/00:00:00. 

import pyspedas
import numpy as np
import pandas as pd
trange=['2010-01-01/00:00:00', '2010-01-02/00:00:00']
varname = 'BX_GSE'
data_omni  = pyspedas.omni.data(trange=['2010-01-01/00:00:00', '2010-01-02/00:00:00'],notplot=True,varformat=varname,time_clip=True)
data = np.array(data_omni[varname]['y'])
unix_time = np.array(data_omni[varname]['x'])
date_time = pd.to_datetime(data_omni[varname]['x'],unit='s')
print(date_time[0])

**Comment by supervised** [comment]
Oh no! That's a bad bug - thank you for catching it!

I just created an issue in the cdflib project for it: [here](https://github.com/MAVENSDC/cdflib/issues/96)

For now, I suggest using astropy to do the time conversion; it should work automatically after installing astropy with:

`pip install astropy`

I'll go ahead and make astropy a required library for pySPEDAS until this is fixed in cdflib, so that it's automatically installed and users don't run into this. The astropy conversion should also speed up load times.

**Comment by supervised** [comment]
This should be fixed in the latest pySPEDAS PyPI release, so updating with:

`pip install pyspedas --upgrade`

and you shouldn't run into this with pySPEDAS anymore. 

I also just added a regression test, so we'll know if this ever comes back. 

Thanks again!

**Comment by xnchu** [comment]
Cool. Thanks for your quick reply. 
Thanks for creating the issue for cdflib. 
The same bug exists in pytplot too.

**Comment by xnchu** [comment]
I am closing the issure since it is resolved. Thanks again.
