### ISSUE TITLE
port tpwrspc to python

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#634]
We have tdpwrspc but not tpwrspc.   We should port it, and provide examples and validation tests.

**Comment by jameswilburlewis** [comment]
By the way, I noticed there's already a pwr_spec routine in pytplot that might be a good starting point.

**Comment by nickssl** [comment]
Done. 

The new files pwrspc.py and tpwrspc.py work the same way as the IDL pwrspc.pro and tpwrspc.pro routines. 

I did not use and made no changes to the pwr_spec routine because the name of that routine is different, and the internal logic is also different (uses signal.periodogram from scipy). Perhaps we should delete this file to avoid confusion.
