### ISSUE TITLE
pyspedas.version() error

### ISSUE THREAD

**Issue by xandrd** [spedas/pyspedas#639]
Steps to reproduce:
```python
import pyspedas
pyspedas.version()
```

```
Traceback (most recent call last):
  File "<ipython-input-5-1c74a217faf0>", line 1, in <module>
    pyspedas.version()
...
  File "C:\work\Codes\SPEDAS\venvs\pyspedas39\lib\site-packages\pkg_resources\__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyspedas' distribution was not found and is required by the application
```

Reason: `pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html `

Python version 3.9

**Comment by jameswilburlewis** [comment]
Yes, we should update to importlib, but that's not why it failed.    If you're running pyspedas out of a git working copy, the metadata from setup.py isn't populated yet.  That happens when setup.py is run to create a new release to upload to pypi.
If you have a fresh environment and install pyspedas with "pip install", pyspedas.version() works as expected:

Python 3.9.18 (main, Sep 11 2023, 08:25:10) 
[Clang 14.0.6 ] on darwin
import pyspedas
pyspedas.version()
13-Nov-23 15:34:24: pyspedas version: 1.4.46

**Comment by jameswilburlewis** [comment]
Just pushed a new version of pyspedas.version() that uses importlib_metadata instead of pkg_resources.
