### ISSUE TITLE
Keyword varnames returns empty dictionary for pyspedas.psp.spc

### ISSUE THREAD

**Issue by srijaniiserprinceton** [spedas/pyspedas#684]
Loading specific `varnames` does not work for me when loading SPC data using `pyspedas`. I see that when I exclude `varnames` then it works (but ofcourse downloads the entire set of variables making it slow) but when I specify some `varname`, it returns an empty dictionary or list.
So, for a certain `tstart` and `tend`  the following snippet works
```
import pyspedas
tstart, tend = '2019-03-30', '2019-04-12'
spc_vars_all = pyspedas.psp.spc(trange=[tstart, tend], datatype='l3i', level='l3', time_clip=True, no_update=False, notplot=True)
```
but this does not
```
spc_vars_one = pyspedas.psp.spc(trange=[tstart, tend], varnames=['psp_spc_vp_fit_RTN'], datatype='l3i', level='l3', time_clip=True, no_update=False, notplot=True)
```

**Comment by jameswilburlewis** [comment]
OK, I figured out what was going on!   In cdf_to_tplot, the 'varnames' values, if provided, are matched with the variable names as they appear in the CDF, which are not necessarily the same as the final tplot names that will be returned.   For PSP SPC data, cdf_to_tplot is passed another parameter, prefix='psp_spc_', which is prepended to the CDF variable names to yield the tplot variable names.   The CDF variables don't have this prefix (so the CDF has 'vp_fit_RTN' rather than 'psp_spc_vp_fit_RTN').  So varnames doesn't match anything in the CDF, and nothing gets returned.

If you use varnames=['vp_fit_RTN'], the call works as expected.

I think cdf_to_tplot should probably be using any prefix or suffix arguments when doing the varnames matching.  I'll open a task to get that fixed...meanwhile, I hope the workaround of stripping the prefixes from the varnames values will work for you.

**Comment by jameswilburlewis** [comment]
See related issue https://github.com/spedas/pyspedas/issues/686

**Comment by srijaniiserprinceton** [comment]
Thanks so much @jameswilburlewis ! Omitting the prefix does the trick for me :)
