### ISSUE TITLE
Unnecessary message "SpacePy must be installed to use this module." 

### ISSUE THREAD

**Issue by nickssl** [spedas/pyspedas#702]
When I use "import pyspedas", I get the message:

"SpacePy must be installed to use this module."

Perhaps this happens because mms_qcotrans was included in the __init__.py files.

I think it is better if this message is shown only when the user tries to use the particular mms module. Also, the message should be more descriptive - it should include the name of the module (mms_qcotrans , mms_cotrans_qrotate).

**Comment by jameswilburlewis** [comment]
I'm not sure why we're even using SpacePy for that.  (There's a bit of a tendency in the PyHC community to leverage capabilities in other packages, rather than reimplementing them....maybe that's part of it.).  In this case, we already have well-tested quaternion interpolation routines in IDL (and I'm pretty sure they're ported to Python as well).   And I think that's the only place in pyspedas that we're using SpacePy.  I think we should just use our own code rather than introducing a dependency on another large, complicated package just to get one feature.

**Comment by nickssl** [comment]
I moved the "import spacepy" commands inside the functions, so now they will not be run every time we import pyspedas. 

This fixes the problem of unnecessary and confusing messages while importing pyspedas.
