### ISSUE TITLE
some trouble

### ISSUE THREAD

**Issue by leeseunguk** [spedas/pyspedas#89]
Trying to call 

thm_fgm = pyspedas.themis.fgm(trange=['2015-10-16/13:06', '2015-10-16/15:07'], probe='d', time_clip=True) 
times, fgm_data = get_data('thd_fgs_gse')

but 

This code did not run.

And the cdf load execution time is quite long. is this normal?

**Comment by supervised** [comment]
Hello - thanks for the bug report! 

The issue here is that these CDFs have an extra depend - which seems to be simply [1, 2, 3] - and that's being returned by get_data (in addition to the times, and B-field values). I suggest using:

```
thm_fgm = pyspedas.themis.fgm(trange=['2015-10-16/13:06', '2015-10-16/15:07'], probe='d', time_clip=True)
fgm_data = get_data('thd_fgs_gse')
```

You can then access the times and B-field values with:

```
>>> fgm_data.times
array([1.44500076e+09, 1.44500076e+09, 1.44500077e+09, ...,
       1.44500801e+09, 1.44500802e+09, 1.44500802e+09])
>>> fgm_data.y
array([[14.464934 ,  8.287867 , 12.734857 ],
       [14.464935 ,  8.287866 , 12.734857 ],
       [14.462239 ,  8.285946 , 12.711245 ],
       ...,
       [ 3.0936048, -3.9471464, 19.264576 ],
       [ 3.0780532, -3.9823644, 19.341436 ],
       [ 3.0966294, -3.957096 , 19.397446 ]], dtype=float32)
```

Returning the tuple also allows you to check that data were returned before doing something with it, e.g., 

```
thm_fgm = pyspedas.themis.fgm(trange=['2015-10-16/13:06', '2015-10-16/15:07'], probe='d', time_clip=True)
fgm_data = get_data('thd_fgs_gse')
if fgm_data is not None:
    ... do something with the data
```

It can take quite some time to load some data, though this one didn't take much time for me. I suggest making sure you're running Astropy 4.2 or later - I think they recently improved time conversion routines in there (which is where the bottleneck is when loading these data). 

Hope this helps!
