### ISSUE TITLE
Installation issues - HDF5 and conda

### ISSUE THREAD

**Issue by rweigel** [spedas/pyspedas#967]
I tried `pip install pyspedas` and got the following error. I was not able to find "HDF5" in a search at https://pyspedas.readthedocs.io/en/latest/index.html. I was able to install after executing `brew install hdf5`. Perhaps document this requirement?

I also tried [`conda install spedas::pyspedas`](https://anaconda.org/SPEDAS/pyspedas) but got `PackagesNotFoundError`. Not sure why this did not work.

```
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /var/folders/jt/sdjwwwys0y5_8p3glv8cmjnw0000gn/T/H5closeoquozx_g.c:1:10: fatal error: 'H5public.h' file not found
      #include "H5public.h"
               ^~~~~~~~~~~~
      1 error generated.
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.10.14 (main, Mar 21 2024, 11:21:31) [Clang 14.0.6 ]
      * Found cython 3.0.11
      * USE_PKGCONFIG: False
      * Found conda env: ``/opt/miniconda3/envs/python3.10.14``
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by jameswilburlewis** [comment]
Hi Bob,

Yes, we've run across that ourselves in the past.  pyspedas and pytplot-mpl-temp don't depend directly on hdf5...it's a few layers deeper in the dependency tree, and I think it's only a compile-time dependency rather than a runtime requirement (maybe why it's not listed as an explicit dependency on NetCDF4, tables, or whatever package it's trying to compile).

Relevant issues (one open, one closed):
https://github.com/spedas/pyspedas/issues/792
https://github.com/spedas/pyspedas/issues/873

pyspedas isn't available yet as a conda package.  I think we need to get the geopack package on conda before that can happen.   

Related issues for pyspedas on conda: 
https://github.com/spedas/pyspedas/issues/496
https://github.com/spedas/pyspedas/issues/275

We have been making a big push, since before PyHC summer school, to improve our new user onboarding experience, including walking folks who may be new to Python through installing Python itself, setting up a Python development environment, and installing/configuring pyspedas.   As you've seen, we still have a lot of work to do in that department...

One aspect of that will be what to do if some outside package can't be installed cleanly via pip:  that's kind of a tall order because setting up compiler tools and installing necessary prerequisite libraries is so platform-dependent.   Having been through some of that already on my Mac, it's difficult to go back and recreate the new user experience for the purpose of documenting the steps, without undoing all the effort I've made to get everything working.  But, we recognize the need and we're working on it!

Related issue:
https://github.com/spedas/pyspedas/issues/623

It does sound like you were able to get past the issue with "brew install hdf5".  We were also able to solve it by doing "conda install h5py",  as described in issue 792.

By all means, please do let us know if you encounter any other installation or configuration hiccups!

**Comment by rweigel** [comment]
Thanks, and I apologize for not searching the issues for "hdf5" - I only searched the documentation and Google for " pyspedas hdf5." (I told students to do in the summer school to search issues before posting, so do as I say, I guess)

**Comment by jameswilburlewis** [comment]
No worries...actually, it's useful for us to know that it's still an issue, and that we'll probably be dealing with it for a while still.
